const NAME_OR_PASSWORD_NOT_NULL = 'NAME_OR_PASSWORD_NOT_NULL'
const NAME_EXISTS = 'NAME_EXISTS'
const NAME_NOT_EXISTS = 'NAME_NOT_EXISTS'
const PASSWORD_INCORRECT = 'PASSWORD_INCORRECT'

module.exports = {
  NAME_OR_PASSWORD_NOT_NULL,
  NAME_EXISTS,
  NAME_NOT_EXISTS,
  PASSWORD_INCORRECT,
}
